import { useEffect,useState } from 'react';
import { Brand } from '../../components/Brand';
import { getSupabase } from '../../lib/supabase';
import { signOut } from '../../lib/auth';
import { portal,message } from './client';
import { emptyProfile, ProfileFields, type Profile } from './ProfileFields';
import { TrainingRequests } from './TrainingRequests';
import { MfaSettings } from './MfaSecurity';
interface Overview{email:string;person:{full_name:string;phone?:string|null}|null;staff:{role:string;display_name:string;active:boolean}|null;profile?:Profile|null}
export function AccountOverview(){const [data,setData]=useState<Overview|null>(null);const [error,setError]=useState('');const [profile,setProfile]=useState(emptyProfile);const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;void portal<Overview>('account.overview').then(value=>{if(live){setData(value);if(new URLSearchParams(window.location.search).get('account')==='confirm'){const clean=new URL(window.location.href);clean.search='';clean.hash='/account';window.history.replaceState(null,'',clean);}setProfile({...emptyProfile,...value.profile});setError('');}}).catch(cause=>live&&setError(message(cause)));return()=>{live=false;};},[revision]);
 async function complete(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await portal('account.complete-profile',{profile});await getSupabase().auth.updateUser({data:{registration_profile:null}});setRevision(v=>v+1);}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 return <main className="simple-shell"><header><Brand/><nav className="portal-actions"><a href="#/">Home</a><a href="#/book">Booking portal</a><a href="#/policies">Policies</a><button className="text-button" onClick={()=>void signOut().then(()=>{window.location.hash='/';})}>Sign out</button></nav></header><section className="simple-card"><p className="eyebrow">Your account</p><h1>{data?.staff?.display_name||data?.person?.full_name||'My account'}</h1>{error&&<p className="alert alert--error" role="alert">{error}<button className="text-button" onClick={()=>setRevision(v=>v+1)}>Retry</button></p>}{!data&&!error&&<p role="status">Loading your account…</p>}{data&&<><p>{data.email}</p>{data.staff?.active&&<section className="panel"><h2>{data.staff.role==='viewer'?'Staff':data.staff.role==='ambassador'?'MS Ambassador':data.staff.role.charAt(0).toUpperCase()+data.staff.role.slice(1)} workspace</h2><p>Your staff access is separate from personal training and booking eligibility.</p><a className="button button--primary" href="#/staff/dashboard">Open staff workspace</a></section>}{data.person?<section className="panel"><h2>Your Makerspace record is linked</h2><p>Your existing training stays on this record. View your passes and book equipment in your booking portal.</p><a className="button button--secondary" href="#/book">Open my booking portal</a></section>:<section className="panel"><h2>{data.staff?'Add a personal Makerspace profile':'Complete your registration'}</h2><p>Staff access works without a student record. To book equipment for yourself, complete a personal profile. Existing trainees should first confirm they are using their registered training email; contact the desk if it differs.</p><form className="portal-form" onSubmit={e=>void complete(e)}><ProfileFields value={profile} onChange={setProfile}/><button className="button button--primary" disabled={busy}>{busy?'Saving…':'Save my profile'}</button></form></section>}{data.person&&<TrainingRequests phone={data.person.phone||''}/>}<div className="portal-actions"><a href="#/password">Change password</a></div><MfaSettings/></>}</section></main>;}
