import { useEffect,useState } from 'react';
import { getSupabase } from '../../lib/supabase';
import { message } from './client';
import { workspaceCache } from '../../lib/workspaceCache';
export function MfaGate({children,required=false}:{children:React.ReactNode;required?:boolean}){
 const [enroll,setEnroll]=useState(false);const [ready,setReady]=useState(false);const [factor,setFactor]=useState('');const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;void (async()=>{const auth=getSupabase().auth;const result=await auth.mfa.getAuthenticatorAssuranceLevel();if(result.error)throw result.error;if(result.data.nextLevel==='aal2'&&result.data.currentLevel!=='aal2'){const factors=await auth.mfa.listFactors();if(factors.error)throw factors.error;const id=factors.data.totp[0]?.id;if(!id)throw new Error('Use staff account recovery to restore your verification method.');if(live)setFactor(id);}else if(required&&result.data.currentLevel!=='aal2'){if(live)setEnroll(true);}if(live)setReady(true);})().catch(cause=>live&&setError(message(cause)));return()=>{live=false;};},[required]);
 async function verify(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const result=await getSupabase().auth.mfa.challengeAndVerify({factorId:factor,code});if(result.error)setError(result.error.message);else{workspaceCache.clear();setFactor('');}setBusy(false);}
 if(enroll)return <main className="simple-shell"><section className="simple-card"><h1>Secure your staff account</h1><p>Staff access requires an authenticator app. Complete setup once, then verify its code when signing in.</p><MfaSettings onEnabled={()=>{setEnroll(false);workspaceCache.clear();}}/><a href="#/account">My account</a></section></main>;
 if(ready&&!factor)return <>{children}</>;
 return <main className="simple-shell"><section className="simple-card"><h1>{factor?'Verify your sign in':'Checking account security'}</h1>{error&&<p className="alert alert--error" role="alert">{error}</p>}{factor&&<form className="portal-form" onSubmit={e=>void verify(e)}><p>Enter the six-digit code from your authenticator app.</p><label className="field">Authenticator code<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label><button className="button button--primary" disabled={busy}>Verify sign in</button></form>}<a href="#/">Home</a></section></main>;
}
export function MfaSettings({onEnabled}:{onEnabled?:()=>void}={}){
 const [factors,setFactors]=useState<Array<{id:string;friendly_name?:string}>>([]);const [enrollment,setEnrollment]=useState<{id:string;qr:string;secret:string}|null>(null);const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);
 async function refresh(){const result=await getSupabase().auth.mfa.listFactors();if(result.error)throw result.error;setFactors(result.data.totp);setReady(true);}
 useEffect(()=>{void refresh().catch(cause=>setError(message(cause)));},[]);
 async function enable(){setBusy(true);setError('');try{const result=await getSupabase().auth.mfa.enroll({factorType:'totp',friendlyName:`KEC authenticator ${new Date().toISOString().slice(0,10)}`,issuer:'KEC Makerspace'});if(result.error)throw result.error;setEnrollment({id:result.data.id,qr:result.data.totp.qr_code,secret:result.data.totp.secret});}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 async function verify(e:React.FormEvent){e.preventDefault();if(!enrollment)return;setBusy(true);setError('');try{const result=await getSupabase().auth.mfa.challengeAndVerify({factorId:enrollment.id,code});if(result.error)throw result.error;setEnrollment(null);setCode('');workspaceCache.clear();await refresh();onEnabled?.();}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);setError('');try{const result=await getSupabase().auth.mfa.unenroll({factorId:id});if(result.error)throw result.error;if(enrollment?.id===id)setEnrollment(null);await refresh();}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 return <section className="panel"><h2>Two-step sign-in</h2><p>Protect your account with an authenticator app. Staff actions require its code after password sign-in. Set this up for every staff account.</p>{error&&<p className="alert alert--error" role="alert">{error}</p>}{factors.map(f=><div className="portal-row" key={f.id}><span>{f.friendly_name||'Authenticator'} · enabled</span><button className="button button--secondary" disabled={busy} onClick={()=>void remove(f.id)}>Remove authenticator</button></div>)}{ready&&!enrollment&&!factors.length&&<button className="button button--secondary" disabled={busy} onClick={()=>void enable()}>Set up authenticator</button>}{enrollment&&<form className="portal-form" onSubmit={e=>void verify(e)}><p>Scan this QR in your authenticator app, then enter its code. Keep this setup secret private.</p><img className="mfa-qr" src={enrollment.qr} alt="Authenticator setup QR"/><details><summary>Enter the setup key manually</summary><code className="break-url">{enrollment.secret}</code></details><label className="field">Authenticator code<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label><div className="button-row"><button className="button button--primary" disabled={busy}>Enable two-step sign-in</button><button className="button button--secondary" type="button" disabled={busy} onClick={()=>void remove(enrollment.id)}>Cancel setup</button></div></form>}</section>;
}
