import { workspaceCache } from '../../lib/workspaceCache';
import { useEffect,useRef,useState } from 'react';
import { StaffTrainingRequests } from './TrainingRequests';
import type { StaffRequest } from './TrainingRequests';
import { TrainingQuizQr } from './TrainingQuizQr';
import { portal,message,dateTime } from './client';
import type { StaffSession } from '../../types/domain';
interface Person{id:string;full_name:string;email:string;safety_training_status:string;waiver_status:string;minor_status:string;}
interface Type{id:string;display_name:string;}
interface Quiz extends Type{duration_minutes:number;pass_mark:number;question_count:number;quiz_certification_mappings:{certification_type_id:string}[];}
interface Session{id:string;display_name?:string;expires_at:string;revoked_at:string|null;capacity:number;trainer_name:string;quiz_id:string;certification_type_id:string;quiz_attempts:{id:string;status:string;passed:boolean}[];}
interface Manual{id:string;trained_on:string;trainer_name:string;outcome:string;evidence:string;people:{full_name:string};certification_types:{display_name:string};}
interface Plan{id:string;name:string;monthly_npr:number;minimum_months:number;}
interface Subscription{id:string;starts_on:string;ends_on:string;status:string;agreed_total_npr:number;people:{full_name:string;email:string};subscription_plans:{name:string};subscription_payments:{amount_npr:number;receipt_reference:string}[];}
interface Material{id:string;name:string;kind:string;unit:string;stock_quantity:number;market_price_npr:number;description:string;active:boolean;}
interface Workspace{requests:StaffRequest[];capabilities:string[];people:Person[];types:Type[];quizzes:Quiz[];sessions:Session[];manual:Manual[];plans:Plan[];subscriptions:Subscription[];materials:Material[];}
const labels:Record<string,string>={training:'Training & QR sessions',access:'Access records & accounts',subscriptions:'External subscriptions',catalog:'Materials & electronics'};
export function OpsWorkspace({session}:{session:StaffSession}){
 const lastKey=useRef('');const [data,setData]=useState<Workspace|null>(null);const [tab,setTab]=useState(['owner','admin'].includes(session.role)?'training':session.capabilities?.[0]||(session.role==='trainer'?'training':''));const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [personId,setPersonId]=useState('');const [editMaterial,setEditMaterial]=useState<Material|null>(null);
 useEffect(()=>{let live=true;const key=`${session.userId}:${session.accessToken}:workspace:${tab}:${query}`;const cached=workspaceCache.peek<Workspace>(key);const sameKey=lastKey.current===key;setData(current=>cached||(sameKey?current:null));lastKey.current=key;setError('');void workspaceCache.get<Workspace>(key,()=>portal<Workspace>('workspace',{search:query,task:tab})).then(result=>{if(live){setData(result);setTab(current=>result.capabilities.includes(current)?current:result.capabilities[0]||'');}}).catch(cause=>live&&setError(message(cause)));return()=>{live=false;};},[revision,query,tab,session.userId,session.accessToken]);
 const currentPerson=data?.people.find(p=>p.id===personId);
 async function submit(event:React.FormEvent<HTMLFormElement>,action:string,extra:Record<string,unknown>={}){event.preventDefault();setError('');setNotice('');setBusy(true);const form=event.currentTarget;try{const body=Object.fromEntries(new FormData(form).entries());await portal(action,{...body,...extra});setNotice('Saved. The action is recorded in audit history.');setRevision(v=>v+1);if(action==='catalog.save')setEditMaterial(null);}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 async function close(s:Session){setBusy(true);try{await portal('training.close',{sessionId:s.id});setRevision(v=>v+1);setNotice('QR admission closed. Already-started attempts keep their own timer.');}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 async function archiveMaterial(id:string){const reason=window.prompt('Reason for archiving this catalog item (at least 10 characters)');if(!reason)return;setBusy(true);try{await portal('catalog.archive',{id,reason});setRevision(v=>v+1);setNotice('Item archived. Stock history is retained.');}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 const peopleOptions=<><option value="">Choose person</option>{data?.people.map(p=><option key={p.id} value={p.id}>{p.full_name} · {p.email}</option>)}</>;
 const typesOptions=<><option value="">Choose certification</option>{data?.types.map(t=><option key={t.id} value={t.id}>{t.display_name}</option>)}</>;
 return <><p className="eyebrow">Your responsibilities</p><h1>Daily operations</h1><p>Signed in as {session.displayName}. Only your assigned tasks appear here. Owners manage responsibilities in Staff access. Training lists only your authorized equipment certifications; assigned trainers see their own session and manual-record history.</p><div className="portal-actions">{data?.capabilities.map(cap=><button className={`button ${tab===cap?'button--primary':'button--secondary'}`} key={cap} onClick={()=>setTab(cap)}>{labels[cap]}</button>)}<a href="#/policies">Policy & tracking guide</a></div>{error&&<p className="alert alert--error" role="alert">{error}</p>}{notice&&<p className="alert" role="status">{notice}</p>}
 {!data?<p>{error?'Use another task or reload to retry.':'Loading responsibilities…'}</p>:!data.capabilities.length?<p>{session.role==='ambassador'?'MS Ambassador role is active. Filament and electronics requests still use the separate system; checkout will be added when it is integrated.':'No operational responsibilities assigned yet. Ask an Owner to enable the tasks you handle.'}</p>:<>
 {tab!=='catalog'&&<form className="portal-actions" onSubmit={e=>{e.preventDefault();setQuery(search);}}><input aria-label="Find a person" placeholder="Find a person by name or email" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button button--secondary">Search people</button><small>Up to 100 matches. Refine your search for larger directories.</small></form>}
 {tab==='training'&&<><StaffTrainingRequests requests={data.requests||[]} onSaved={()=>setRevision(v=>v+1)} admin={['owner','admin'].includes(session.role)}/><section className="panel"><h2>Quiz QR sessions</h2><p>Customize the session label, quiz, admission window and participant limit. Students use their own account to join.</p><TrainingQuizQr onCreated={()=>setRevision(v=>v+1)}/></section>
 <section className="panel"><h2>Recent QR sessions</h2>{data.sessions.map(s=><article className="portal-row" key={s.id}><div><strong>{s.display_name||data.quizzes.find(q=>q.id===s.quiz_id)?.display_name||'Quiz'} · {s.trainer_name}</strong><p>{s.revoked_at?'Closed':new Date(s.expires_at)<new Date()?'Expired':'Open'} · closes {dateTime(s.expires_at)} · {s.quiz_attempts.length}/{s.capacity} joined · {s.quiz_attempts.filter(a=>a.passed).length} passed</p></div>{!s.revoked_at&&new Date(s.expires_at)>new Date()&&<button className="button button--secondary" disabled={busy} onClick={()=>void close(s)}>Close admission</button>}</article>)}</section>
 <section className="panel"><h2>Record training manually</h2><p>Use this for documented hands-on assessments or historical passes. “Passed” grants the selected equipment certificate. Attendance alone does not. Safety and waiver verification stay separate.</p><form className="portal-form" onSubmit={e=>void submit(e,'training.manual')}><label className="field">Person<select name="personId" required>{peopleOptions}</select></label><label className="field">Equipment certification<select name="certificationTypeId" required>{typesOptions}</select></label><label className="field">Training date<input name="trainedOn" type="date" required max={new Date().toISOString().slice(0,10)}/></label><label className="field">Trainer name<input name="trainerName" required defaultValue={session.displayName}/></label><label className="field">Outcome<select name="outcome"><option value="attended">Attended only</option><option value="passed">Passed — issue certification</option><option value="not_passed">Not passed</option></select></label><label className="field">Evidence / assessment reference<textarea name="evidence" required minLength={10} maxLength={1000} placeholder="What was assessed, who confirmed it, and where the evidence is kept"/></label><button className="button button--primary" disabled={busy}>Save manual training record</button></form><h3>Manual record history</h3>{data.manual.map(m=><article className="portal-row" key={m.id}><div><strong>{m.people.full_name} · {m.certification_types.display_name}</strong><p>{m.trained_on} · {m.trainer_name} · {m.outcome}</p><p>{m.evidence}</p></div></article>)}</section></>}
 {tab==='access'&&<><section className="panel"><h2>Add a new trainee / client</h2><p>Search first to avoid duplicating an existing person. Use the same email for their account. New records start with unverified prerequisites.</p><form className="portal-form" onSubmit={e=>void submit(e,'access.create')}><label className="field">Full name<input name="fullName" required/></label><label className="field">Email<input name="email" type="email" required/></label><label className="field">Category<select name="category">{['kec_student','kec_staff','other_college_student','business_external','member_non_kec','outreach_minor'].map(c=><option value={c} key={c}>{c.replaceAll('_',' ')}</option>)}</select></label><label className="field">Roll number<input name="rollNumber"/></label><label className="field">Organization<input name="organization"/></label><label className="field">Phone<input name="phone"/></label><button className="button button--primary" disabled={busy}>Add record</button></form></section><section className="panel"><h2>Review one-time access records</h2><p>Record what you verified from existing evidence. Do not make people repeat equipment training to fill missing administrative fields.</p><label className="field">Person<select value={personId} onChange={e=>setPersonId(e.target.value)}>{peopleOptions}</select></label>{currentPerson&&<form className="portal-form" key={personId} onSubmit={e=>void submit(e,'access.verify',{personId})}><label className="field">General safety<select name="safety" defaultValue={currentPerson.safety_training_status}>{['unknown','verified','revoked'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Waiver<select name="waiver" defaultValue={currentPerson.waiver_status}>{['unknown','verified','revoked'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Age record<select name="age" defaultValue={currentPerson.minor_status}>{['unknown','adult','minor'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Evidence / review note<textarea name="reason" required minLength={10} maxLength={1000}/></label><button className="button button--primary" disabled={busy}>Save verified records</button></form>}</section><section className="panel"><h2>Send an account invitation</h2><p>Existing trainees keep their passes. Send a setup link, for a new account. Email setup must be configured first. Existing users can use Forgot password; invitations never overwrite their passwords.</p><form className="portal-form" onSubmit={e=>void submit(e,'accounts.invite')}><label className="field">Person<select name="personId" required>{peopleOptions}</select></label><label className="field">Invitation type<select name="mode"><option value="link">Email setup link</option></select></label><button className="button button--primary" disabled={busy}>Send account email</button></form></section></>}
 {tab==='subscriptions'&&<><section className="panel"><h2>Start or renew an external subscription</h2><p>Plans are equipment-specific. A renewal is a new agreement starting when the previous one ends. Subscription end dates are exclusive. Materials and training records stay separate.</p><form className="portal-form" onSubmit={e=>void submit(e,'subscriptions.add')}><label className="field">Client<select name="personId" required>{peopleOptions}</select></label><label className="field">Plan<select name="planId" required><option value="">Choose plan</option>{data.plans.map(p=><option value={p.id} key={p.id}>{p.name.replaceAll('_',' ')} · NPR {p.monthly_npr}/month</option>)}</select></label><label className="field">Starts on<input type="date" name="startsOn" required/></label><label className="field">Calendar months<input type="number" name="months" min="3" max="36" defaultValue="3" required/></label><label className="field">Agreement / client reference<input name="note" required maxLength={500}/></label><button className="button button--primary" disabled={busy}>Record subscription</button></form></section><section className="panel"><h2>Subscription ledger</h2>{data.subscriptions.map(s=>{const paid=s.subscription_payments.reduce((sum,p)=>sum+Number(p.amount_npr),0);const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kathmandu'});const state=s.status==='cancelled'?'cancelled':today<s.starts_on?'upcoming':today>=s.ends_on?'expired':'active';return <article className="subscription-card" key={s.id}><h3>{s.people.full_name} · {s.subscription_plans.name.replaceAll('_',' ')}</h3><p>{s.starts_on} → {s.ends_on} · {state}</p><p>Agreed NPR {s.agreed_total_npr} · paid NPR {paid} · balance NPR {Number(s.agreed_total_npr)-paid}</p><details><summary>Record payment / view receipts</summary>{s.subscription_payments.map(p=><p key={p.receipt_reference}>{p.receipt_reference}: NPR {p.amount_npr}</p>)}<form className="portal-form" onSubmit={e=>void submit(e,'subscriptions.payment',{subscriptionId:s.id})}><label className="field">Amount (NPR)<input type="number" min="0.01" step="0.01" required name="amount"/></label><label className="field">Receipt reference<input required name="receipt"/></label><label className="field">Paid on<input type="date" required name="paidOn"/></label><button className="button button--primary" disabled={busy}>Record payment</button></form></details>{s.status==='active'&&<details><summary>Cancel subscription</summary><form onSubmit={e=>void submit(e,'subscriptions.cancel',{subscriptionId:s.id})}><label className="field">Cancellation reason<input name="reason" required/></label><button className="button button--secondary" disabled={busy}>Cancel subscription</button></form></details>}</article>;})}</section></>}
 {tab==='catalog'&&<><section className="panel"><h2>{editMaterial?'Edit stock item':'Publish a stock item'}</h2><p>These items appear on the public catalog and can be linked or embedded on the GitHub website. Enter actual stock and market price; the catalog calculates the external 10% materials markup.</p><form className="portal-form" key={editMaterial?.id||'new'} onSubmit={e=>void submit(e,'catalog.save',{id:editMaterial?.id,active:editMaterial?.active??true})}><label className="field">Name<input name="name" defaultValue={editMaterial?.name} required/></label><label className="field">Kind<select name="kind" defaultValue={editMaterial?.kind||'filament'}><option value="filament">Filament</option><option value="material">Material</option><option value="electronics">Electronics</option></select></label><label className="field">Unit<input name="unit" placeholder="g, sheet, piece…" defaultValue={editMaterial?.unit} required/></label><label className="field">Quantity<input name="stock" type="number" step="0.001" min="0" defaultValue={editMaterial?.stock_quantity||0} required/></label><label className="field">Market price NPR / unit<input name="price" type="number" step="0.01" min="0" defaultValue={editMaterial?.market_price_npr} required/></label><label className="field">Description<textarea name="description" defaultValue={editMaterial?.description}/></label><button className="button button--primary" disabled={busy}>Save catalog item</button>{editMaterial&&<button type="button" className="button button--secondary" onClick={()=>setEditMaterial(null)}>Cancel edit</button>}</form></section><section className="panel">{data.materials.map(m=><article className="portal-row" key={m.id}><p>{m.active?'':'Archived · '}{m.name} · {m.stock_quantity} {m.unit} · NPR {m.market_price_npr}/{m.unit}</p><button className="button button--secondary" onClick={()=>setEditMaterial(m)}>Edit</button>{session.role==='owner'&&m.active&&<button className="button button--secondary" disabled={busy} onClick={()=>void archiveMaterial(m.id)}>Archive</button>}</article>)}</section></>}
 </>}</>;
}
