import { Brand } from '../../components/Brand';
export function Policies(){return <main className="portal-shell"><header className="portal-header"><Brand/><nav><a href="#/account">My bookings</a><a href="#/catalog">Equipment & materials</a><a href="#/staff/dashboard">Staff workspace</a></nav></header><p className="eyebrow">Policy Book · Version 1.1 · August 2026</p><h1>Your space to create.</h1><p className="lead">“If you can dream, you can design.” Get trained. Get access. Get building.</p><p>This guide explains the policy and how this app records it. Equipment SOPs remain authoritative for operating each machine. Contact kec.innovation@kecktm.edu.np about a discrepancy.</p>
 <section className="panel"><h2>Getting access</h2><p><strong>Path A:</strong> Express interest or visit → one-time safety training and waiver → hands-on equipment training → supervised quiz → permanent equipment certification.</p><p><strong>Path B:</strong> Complete the same one-time safety and waiver, then use design workstations and collaboration areas freely. Fabrication equipment still requires certification. Tables are not booked here.</p><p><strong>Path C:</strong> Already certified? Keep your existing safety and waiver record. Train and qualify only on the new equipment.</p><p>Existing passes are preserved. Missing migration details need evidence correction, not repeat equipment quizzes. Certification has no routine expiry; staff can suspend or revoke it for a violation.</p><p><strong>Under 18:</strong> Supervised outreach events or workshops only. A guardian signature does not authorize independent equipment use.</p></section>
 <section className="panel"><h2>How we track the rules</h2><div className="table-scroll"><table className="data-table"><thead><tr><th>Policy</th><th>System record / enforcement</th></tr></thead><tbody>
 <tr><td>Safety, waiver and adulthood</td><td>Separate staff-verified records. Missing or revoked prerequisites block independent booking and QR assessments. Account creation alone grants no equipment access.</td></tr>
 <tr><td>Equipment training</td><td>Server-graded assessments and dated manual training evidence. Passed results activate the authorized certification; a pass cannot silently override a suspended or revoked certificate.</td></tr>
 <tr><td>Supervised quizzes</td><td>Trainer chooses a quiz and its mapped certification, QR admission expiry and capacity. One attempt per person per session; answers and time limits checked on the server. QR admission expiry and the attempt timer are separate.</td></tr>
 <tr><td>Quiz duration discrepancy</td><td>The supplied book says 10 minutes; the earlier approved app specification uses 8 minutes and 16/20. The app retains the approved 8-minute configuration until the team reconciles these documents. Each quiz shows its configured time and pass mark.</td></tr>
 <tr><td>Booking priority</td><td>KEC students/staff first (rank 10), non-KEC members second (20), other college/business users standard (30). These are category labels, not merit scores. The app confirms the first valid atomic booking; staff handle competing requests for an open slot. It does not run a priority queue or displace confirmed bookings.</td></tr>
 <tr><td>6-hour maximum and opening hours</td><td>Database validates duration, active machine, certifications, opening hours and recorded closures. Staff can approve after-hours use with a reason, while prerequisites still apply. Longer-than-six-hour arrangements need staff planning; this app never creates a single longer session.</td></tr>
 <tr><td>Cancellation and attendance</td><td>Less than 2 hours’ notice is flagged. Staff record check-in, completion or no-show; a slot may be released after 15 minutes late. No automatic penalty or ban for one incident.</td></tr>
 <tr><td>Fair use and reduced capacity</td><td>Staff monitor bookings and ask users to release excess reservations when a machine type loses capacity. Consecutive advance-booking limits and reduced-capacity release are staff-managed in this release; no automatic tier arbitration is claimed.</td></tr>
 <tr><td>External subscriptions</td><td>Named equipment scope, pricing category, at least 3 calendar months, agreement reference, dates and payment receipts. Expiry is calculated from the end date. A subscription does not replace training. Hourly arrangements remain available through the desk.</td></tr>
 <tr><td>Permissions and audit</td><td>Owners assign training, access records, subscription or catalog responsibilities. Server checks permissions. Staff changes and training evidence are recorded; students see only their own records.</td></tr>
 <tr><td>Google Calendar</td><td>Optional display mirror of app bookings. The app database is authoritative. Creating or editing a Google event does not create or change a booking here.</td></tr>
 </tbody></table></div></section>
 <section className="portal-grid"><article className="panel"><h2>Safety and conduct</h2><p>Operate only certified equipment. Never leave it unattended, especially the laser cutter; use the extractor and required PPE. Test unfamiliar settings on scrap, keep exits clear, know the emergency stop, and report injuries, near-misses and faults immediately.</p><p>Check each equipment SOP and its material list. PVC, vinyl, foam and chlorine-containing plastics are prohibited on the laser cutter. Ask before bringing your own materials or using an unfamiliar process.</p><p>Clean equipment and return tools after every session. Respect beginners and everyone in the space. Harassment, discrimination and gatekeeping have zero tolerance. Non-certified observers must not operate equipment.</p></article><article className="panel"><h2>Fees and ownership</h2><p>KEC students and staff: equipment use and training free; materials at market price. Other users: published equipment/training fees and market price +10% for materials. Confirm external rates with the desk.</p><p>Subscriptions cover their named equipment category; all-equipment plans state whether the scanner is included. Materials are separate. Catalog quantities are staff-maintained stock records.</p><p>Your own designs made with your paid materials belong to you. Agree additional staff assistance, sponsored-resource or partner ownership terms in writing before starting. Tell the team if you do not want your likeness or project featured.</p></article></section>
 <section className="panel"><h2>Violations, suspension and appeals</h2><p>Minor or first-time issues are normally handled through a conversation. Safety violations pause the session immediately. Repeated or serious violations may suspend a certification, advance bookings or all access. Cleaning failures are discussed on the first two occasions; a third can lead to formal action. An advance-booking suspension alone does not remove otherwise eligible walk-in access.</p><p>Staff assess incidents and appeals. The app does not decide disciplinary outcomes. Contact the Makerspace team with your account of what happened and the outcome you seek; ask for an expected review timeline.</p><p>Prohibited: uncertified machine operation; weapons or harmful components; illegal uses; counterfeit or infringing goods for commercial distribution; unsafe materials; unattended equipment or bypassed safety features; and scaled commercial production without prior arrangement.</p></section>
 <section className="panel"><h2>Visit the Makerspace</h2><p>Monday–Wednesday 09:00–19:00 · Thursday 09:00–18:00 · Friday–Sunday 09:00–17:00. Public holidays closed; staff must enter closures in the schedule. After-hours access is by arrangement for certified users.</p><p>3rd floor, new block, Kathmandu Engineering College campus. A team member is on desk during posted hours.</p><p><a href="mailto:kec.innovation@kecktm.edu.np">kec.innovation@kecktm.edu.np</a> · <a href="https://kec-innovation.github.io/makerspace">Makerspace website, equipment SOPs and community links</a></p><p>The same safety and conduct rules apply to students, external visitors, staff, admins, interns and ambassadors.</p></section></main>;}
