import { useEffect,useState } from 'react';
import { Brand } from '../../components/Brand';
import { getSupabase } from '../../lib/supabase';
import { navigate } from '../../lib/hashRouter';
import { EquipmentAvailability } from './EquipmentAvailability';
import { localDateTimeValue } from '../admin/adminShared';
import { portal,message,dateTime } from './client';
import { certificationIssueLabel } from '../../lib/certificationDate';
interface Person {full_name:string;email:string;category:string;active:boolean;booking_privilege_active:boolean;safety_training_status:string;waiver_status:string;minor_status:string;}
interface Certificate {id:string;status:string;issued_at:string|null;certification_types:{id:string;display_name:string};}
interface Booking {id:string;booking_reference:string;starts_at:string;ends_at:string;status:string;equipment:{display_name:string};}
interface Subscription {id:string;starts_on:string;ends_on:string;status:string;agreed_total_npr:number;subscription_plans:{name:string};subscription_payments:{amount_npr:number}[];}
interface Equipment {id:string;display_name:string;external_allowed:boolean;max_booking_minutes:number;equipment_certification_requirements:{certification_type_id:string}[];}
interface Dashboard {person:Person;certifications:Certificate[];bookings:Booking[];subscriptions:Subscription[];equipment:Equipment[];attempts:{id:string;score:number;max_score:number;status:string;quizzes:{display_name:string}}[];}
export function StudentPortal({trainingToken}:{trainingToken?:string}){
 const [data,setData]=useState<Dashboard|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
 const [equipmentId,setEquipmentId]=useState('');const [start,setStart]=useState(localDateTimeValue(1));const [end,setEnd]=useState(localDateTimeValue(2));const [purpose,setPurpose]=useState('');
 useEffect(()=>{let live=true;void portal<Dashboard>('me.dashboard').then(result=>{if(live){setData(result);setError('');}}).catch(cause=>live&&setError(message(cause)));return()=>{live=false;};},[revision]);

 async function run(task:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await task();setRevision(v=>v+1);}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 async function join(){if(!trainingToken)return;const saved=sessionStorage.getItem(`kec-attempt-${trainingToken}`);if(saved){navigate(`/quiz/${saved}`);return;}const result=await portal<{attemptToken:string}>('training.join',{sessionToken:trainingToken});sessionStorage.setItem(`kec-attempt-${trainingToken}`,result.attemptToken);navigate(`/quiz/${result.attemptToken}`);}
 const eligible=data?.equipment.filter(machine=>(['kec_student','kec_staff'].includes(data.person.category)||machine.external_allowed)&&machine.equipment_certification_requirements.every(requirement=>data.certifications.some(c=>c.status==='active'&&c.certification_types.id===requirement.certification_type_id)))||[];
 const ready=data?.person.active&&data.person.booking_privilege_active&&data.person.safety_training_status==='verified'&&data.person.waiver_status==='verified'&&data.person.minor_status==='adult';
 return <main className="portal-shell"><header className="portal-header"><Brand/><nav><a href="#/account">My account</a><a href="#/policies">Policies</a><a href="#/catalog">Materials</a><a href="#/staff/dashboard">Staff</a><a href="#/password">Change password</a><button className="text-button" onClick={()=>void getSupabase().auth.signOut()}>Sign out</button></nav></header>
 <p className="eyebrow">Get trained. Get access. Get building.</p><h1>{data?`Hello, ${data.person.full_name}.`:'Your Makerspace'}</h1>{error&&<div className="alert alert--error" role="alert">{error}<button className="text-button" onClick={()=>setRevision(v=>v+1)}>Retry</button></div>}{notice&&<p className="alert" role="status">{notice}</p>}
 {trainingToken&&<section className="panel"><h2>Join your supervised training quiz</h2><p>Your trainer selected the quiz and certification. Starting begins your assessment timer. Stay with your trainer; closing the QR does not shorten an attempt already started.</p><button className="button button--primary" disabled={busy||!data} onClick={()=>void run(join)}>Start / resume my quiz</button></section>}
 {data&&<><section className="portal-grid"><article className="panel"><h2>Your equipment training</h2>{data.certifications.length?data.certifications.map(c=><p key={c.id}><strong>{c.certification_types.display_name}</strong> · {c.status}<br/><small>{certificationIssueLabel(c.issued_at)} · no routine expiry</small></p>):<p>No equipment certification yet. Join a supervised session or ask staff to record your completed training.</p>}</article><article className="panel"><h2>One-time access records</h2><p>Safety training: <strong>{data.person.safety_training_status}</strong></p><p>Waiver: <strong>{data.person.waiver_status}</strong></p><p>Age record: <strong>{data.person.minor_status}</strong></p><p>{ready?'Your booking prerequisites are verified.':'Ask staff to correct missing records. An existing equipment pass does not need repeating.'}</p></article></section>
 <section className="panel"><h2>Book equipment</h2><p>All times are Nepal time. Maximum session: 6 hours, or the machine’s shorter limit. Confirmed bookings are protected; the app checks conflicts atomically. For competing open-slot priority requests, contact staff.</p><p>Passing activates the relevant certification immediately. Verified safety, waiver and adult records are also required. External users can use their subscription or arrange hourly payment with the desk.</p>
 <form className="portal-form" onSubmit={event=>{event.preventDefault();void run(async()=>{const result=await portal<{bookingReference:string}>('me.book',{equipmentId,startsAt:new Date(start+'+05:45').toISOString(),endsAt:new Date(end+'+05:45').toISOString(),purpose});setNotice(`Confirmed: ${result.bookingReference}. Your booking is saved in the app.`);});}}>
 <label className="field">Certified equipment<select required value={equipmentId} onChange={e=>setEquipmentId(e.target.value)}><option value="">Choose equipment</option>{eligible.map(machine=><option value={machine.id} key={machine.id}>{machine.display_name} · up to {machine.max_booking_minutes/60} hours</option>)}</select></label>{equipmentId&&<EquipmentAvailability key={equipmentId} equipmentId={equipmentId} equipmentName={eligible.find(machine=>machine.id===equipmentId)?.display_name||'Equipment'} date={start.slice(0,10)||localDateTimeValue().slice(0,10)} start={start} end={end} maxMinutes={eligible.find(machine=>machine.id===equipmentId)?.max_booking_minutes||360} revision={revision} onDateChange={date=>{setStart(date+start.slice(10));setEnd(date+end.slice(10));}} onChoose={(starts,ends)=>{setStart(starts);setEnd(ends);}}/>}<label className="field">Starts (Nepal)<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">Ends (Nepal)<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="field">Project / purpose<input maxLength={500} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><button className="button button--primary" disabled={busy||!ready||!equipmentId}>Confirm booking</button></form>
 </section>
 <section className="panel"><h2>My bookings</h2><p>Cancel at least 2 hours ahead. Late cancellations are recorded for staff review.</p>{data.bookings.length===0&&<p>No bookings yet.</p>}{data.bookings.map(booking=><article className="portal-row" key={booking.id}><div><strong>{booking.equipment.display_name} · {booking.booking_reference}</strong><p>{dateTime(booking.starts_at)} — {dateTime(booking.ends_at)}</p><span>{booking.status}</span></div>{booking.status==='confirmed'&&<button className="button button--secondary" disabled={busy} onClick={()=>void run(async()=>{await portal('me.cancel',{bookingId:booking.id});setNotice('Booking cancelled.');})}>Cancel booking</button>}</article>)}</section>
 <section className="panel"><h2>My subscriptions</h2>{data.subscriptions.length===0?<p>No paid subscription on file. KEC students and staff use equipment and training free; materials are separate.</p>:data.subscriptions.map(s=>{const paid=s.subscription_payments.reduce((sum,p)=>sum+Number(p.amount_npr),0);const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kathmandu'});const status=s.status==='cancelled'?'cancelled':today<s.starts_on?'upcoming':today>=s.ends_on?'expired':'active';return <article className="portal-row" key={s.id}><div><strong>{s.subscription_plans.name}</strong><p>{s.starts_on} to {s.ends_on} (end date excluded) · {status}</p><p>Agreed NPR {s.agreed_total_npr} · recorded payments NPR {paid} · balance NPR {Number(s.agreed_total_npr)-paid}</p></div></article>;})}</section>
 <section className="panel"><h2>My quiz results</h2>{data.attempts.map(a=><p key={a.id}>{a.quizzes.display_name} · {a.status}{a.score!==null?` · ${a.score}/${a.max_score}`:''}</p>)}</section></>}
 </main>;
}
