import { useEffect,useRef,useState } from 'react';
import { workspaceCache } from '../../lib/workspaceCache';
import { getSupabase } from '../../lib/supabase';
import { Modal } from '../../components/Modal';
import { portal,message,dateTime } from './client';
interface Options{types:{id:string;display_name:string}[];quizzes:{id:string;display_name:string;duration_minutes:number;pass_mark:number;question_count:number;quiz_certification_mappings:{certification_type_id:string}[]}[]}
export function TrainingQuizQr({onCreated}:{onCreated?:()=>void}){
 const [open,setOpen]=useState(false);const [options,setOptions]=useState<Options|null>(null);const [quizId,setQuizId]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const lock=useRef(false);const [qr,setQr]=useState<{id:string;url:string;expiresAt:string;displayName:string;image:string}|null>(null);const [closed,setClosed]=useState(false);
 useEffect(()=>{if(!open)return;let live=true;setError('');void getSupabase().auth.getSession().then(({data})=>{const key=`${data.session?.user.id}:${data.session?.access_token}:training-qr-options`;const cached=workspaceCache.peek<Options>(key);if(live&&cached)setOptions(cached);return workspaceCache.get<Options>(key,()=>portal<Options>('training.qr-options'));}).then(data=>live&&setOptions(data)).catch(cause=>live&&setError(message(cause)));return()=>{live=false;};},[open]);
 const quiz=options?.quizzes.find(row=>row.id===quizId);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{const data=await portal<{id:string;url:string;expiresAt:string;displayName:string}>('training.open',Object.fromEntries(new FormData(e.currentTarget)));setQr({...data,image:await (await import('qrcode')).default.toDataURL(data.url,{width:600,margin:3,errorCorrectionLevel:'M'})});setClosed(false);onCreated?.();}catch(cause){setError(message(cause));}finally{lock.current=false;setBusy(false);}}
 async function close(){if(!qr||lock.current)return;lock.current=true;setBusy(true);try{await portal('training.close',{sessionId:qr.id});setClosed(true);setNotice('Admission closed. Attempts already started keep their own timer.');onCreated?.();}catch(cause){setError(message(cause));}finally{lock.current=false;setBusy(false);}}
 return <><button className="button button--primary" onClick={()=>setOpen(true)}>Create quiz QR</button><Modal title="Create quiz QR" open={open} onClose={()=>setOpen(false)}><p>Open admission after hands-on training. Students sign in, scan the QR and start their own assessment. The admission window is separate from the quiz timer.</p>{error&&<p className="alert alert--error" role="alert">{error}</p>}{notice&&<p className="alert" role="status">{notice}</p>}{!options?<p role="status">{error?'Close and reopen to retry.':'Loading authorized quizzes…'}</p>:<form className="portal-form" onSubmit={e=>void create(e)}><label className="field">Session label (optional)<input name="sessionName" maxLength={120} placeholder="For example, Friday external laser training"/></label><label className="field">Quiz<select required name="quizId" value={quizId} onChange={e=>setQuizId(e.target.value)}><option value="">Choose quiz</option>{options.quizzes.map(row=><option key={row.id} value={row.id}>{row.display_name} · {row.duration_minutes} min · {row.pass_mark}/{row.question_count}</option>)}</select></label><label className="field">Certification awarded<select required key={quizId} name="certificationTypeId"><option value="">Choose mapped certification</option>{options.types.filter(type=>quiz?.quiz_certification_mappings.some(mapping=>mapping.certification_type_id===type.id)).map(type=><option key={type.id} value={type.id}>{type.display_name}</option>)}</select></label><div className="form-grid"><label className="field">QR admission window (minutes)<input required type="number" name="minutes" min="1" max="120" defaultValue="15"/></label><label className="field">Maximum participants<input required type="number" name="capacity" min="1" max="200" defaultValue="25"/></label></div><button className="button button--primary" disabled={busy}>{busy?'Creating…':'Create training QR'}</button></form>}{qr&&<section className="qr-card" aria-label="Generated training QR"><h3>{qr.displayName||'Training quiz QR'}</h3><img src={qr.image} width="300" height="300" alt="Scan to join the authorized training quiz"/><p>{closed?'Admission closed':`Admission closes ${dateTime(qr.expiresAt)} (Nepal)`}</p><p className="break-url">{qr.url}</p><div className="portal-actions"><button className="button button--secondary" onClick={()=>void navigator.clipboard.writeText(qr.url).then(()=>setNotice('Training link copied.')).catch(()=>setError('Copy the displayed link manually.'))}>Copy link</button><a className="button button--secondary" href={qr.image} download="KEC-training-QR.png">Download QR</a>{!closed&&<button className="button button--secondary" disabled={busy} onClick={()=>void close()}>Close admission</button>}</div><p>The QR uses your configured Makerspace app address. Eligible participants receive certification only after passing the assessment.</p></section>}</Modal></>;
}
