import { useEffect,useRef,useState } from 'react';
import { portal,message,dateTime } from './client';
import { nepalInputValue } from '../../lib/availabilityTimeline';
import { nepalTimestamp,requiresContact } from '../../lib/trainingAppointment';
export interface RequestRow{id:string;updated_at?:string;certification_type_id?:string;status:string;contact_phone:string;availability:string;student_note:string;preferred_date?:string|null;preferred_start?:string|null;preferred_end?:string|null;scheduled_at:string|null;scheduled_end_at?:string|null;assigned_trainer_id?:string|null;assigned_trainer?:{display_name:string}|null;staff_note:string;created_at:string;certification_types:{display_name:string}}
export interface StaffRequest extends RequestRow{people:{full_name:string;email:string;category?:string;organization?:string|null}}
export interface TrainerOption{userId:string;displayName:string;trainingTypeIds:string[]}
interface Data{types:Array<{id:string;display_name:string}>;requests:RequestRow[]}
export function HelpDesk(){return <p className="help-desk">Questions about training, your records or special arrangements? <a href="mailto:kec.innovation@kecktm.edu.np">Ask the Makerspace help desk</a> or <a href="https://kec-innovation.github.io/makerspace/contact.html" target="_blank" rel="noopener noreferrer">view contact details</a>.</p>;}
function Appointment({row}:{row:RequestRow}){return <>{row.scheduled_at&&<p><strong>{row.status==='scheduled'?'Confirmed session':'Session'}:</strong> {dateTime(row.scheduled_at)}{row.scheduled_end_at&&` – ${dateTime(row.scheduled_end_at)}`} (Nepal){row.assigned_trainer&&<><br/>Trainer: {row.assigned_trainer.display_name}</>}</p>}<p><strong>Preferred time:</strong> {row.availability}</p>{row.staff_note&&<p><strong>Staff instructions:</strong> {row.staff_note}</p>}</>;}
export function TrainingRequests({phone='',category=''}:{phone?:string;category?:string}){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;setError('');void portal<Data>('account.training').then(value=>live&&setData(value)).catch(cause=>live&&setError(message(cause)));return()=>{live=false;};},[revision]);
 async function request(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');const form=e.currentTarget;try{const body=Object.fromEntries(new FormData(form));if(String(body.preferredEnd)<=String(body.preferredStart))throw new Error('Choose an end time after the start.');await portal('account.request-training',body);setNotice('Request sent. This is not a confirmed booking. Staff will assign a trainer and post the accepted time here, contacting you first if the time changes.');form.reset();setRevision(v=>v+1);}catch(cause){setError(message(cause));}finally{lock.current=false;setBusy(false);}}
 async function cancel(id:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await portal('account.cancel-training',{requestId:id});setNotice('Training request cancelled. Your history is retained.');setRevision(v=>v+1);}catch(cause){setError(message(cause));}finally{lock.current=false;setBusy(false);}}
 const external=['other_college_student','business_external','member_non_kec'].includes(category);
 return <section className="panel"><h2>{external?'Training for external clients':'Request equipment training'}</h2><p>Choose laser cutting, 3D printing or another available training. Give a preferred day and time window. Staff will try to accommodate it, or contact you to agree on another time. Your confirmed session will appear below.</p><p>All times are Nepal time. Training requests are separate from equipment bookings, subscriptions and certification.</p><HelpDesk/>{error&&<p className="alert alert--error" role="alert">{error}</p>}{notice&&<p className="alert" role="status">{notice}</p>}{!data?<p role="status">{error?'Reload your account to retry.':'Loading training options…'}</p>:<><form className="portal-form" onSubmit={e=>void request(e)}><label className="field">Equipment training<select required name="certificationTypeId" defaultValue=""><option value="">Choose what you want to learn</option>{data.types.map(type=><option key={type.id} value={type.id}>{type.display_name}</option>)}</select></label><label className="field">Contact number<input required type="tel" autoComplete="tel" name="phone" minLength={7} maxLength={40} defaultValue={phone}/></label><div className="form-grid"><label className="field field--full">Preferred date (Nepal)<input required type="date" name="preferredDate" min={nepalInputValue(new Date()).slice(0,10)}/></label><label className="field">Available from<input required type="time" name="preferredStart"/></label><label className="field">Available until<input required type="time" name="preferredEnd"/></label></div><label className="field">Alternative days / times (optional)<textarea name="availability" maxLength={900} placeholder="Other times you can attend, if your first choice is unavailable"/></label><label className="field">What do you want to make? / questions<textarea name="note" maxLength={1000}/></label><button className="button button--primary" disabled={busy}>{busy?'Sending…':'Send training request'}</button></form><h3>Your training requests</h3>{!data.requests.length&&<p>No training requests yet.</p>}{data.requests.map(row=><article className="training-request-card" key={row.id}><div className="panel-heading"><strong>{row.certification_types.display_name}</strong><span className="status-badge">{row.status==='pending'?'Awaiting staff confirmation':row.status}</span></div><Appointment row={row}/>{['pending','scheduled'].includes(row.status)&&<button className="button button--secondary button--small" disabled={busy} onClick={()=>void cancel(row.id)}>Cancel training request</button>}</article>)}</>}</section>;
}
export function RequestEditor({request,onSaved,admin=false,trainers=[]}:{request:StaffRequest;onSaved:()=>void;admin?:boolean;trainers?:TrainerOption[]}){
 const [status,setStatus]=useState(admin?request.status:'completed');const [start,setStart]=useState(request.scheduled_at?nepalInputValue(request.scheduled_at):request.preferred_date?`${request.preferred_date}T${request.preferred_start?.slice(0,5)}`:'');const [end,setEnd]=useState(request.scheduled_end_at?nepalInputValue(request.scheduled_end_at):request.preferred_date?`${request.preferred_date}T${request.preferred_end?.slice(0,5)}`:'');const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState('');
 const changed=status==='scheduled'&&start&&end&&requiresContact(request,nepalTimestamp(start)!,nepalTimestamp(end)!);
 const ended=request.status==='scheduled'&&new Date(request.scheduled_end_at||request.scheduled_at||'').getTime()<=Date.now();
 const editable=['pending','scheduled'].includes(request.status)&&(admin||ended);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const body=Object.fromEntries(new FormData(e.currentTarget));await portal('training.request-update',{requestId:request.id,status,scheduledAt:status==='scheduled'?nepalTimestamp(start):null,scheduledEndAt:status==='scheduled'?nepalTimestamp(end):null,trainerId:body.trainerId||null,note:body.note,contactConfirmed:body.contactConfirmed==='on'});onSaved();}catch(cause){setError(message(cause));}finally{lock.current=false;setBusy(false);}}
 return <article className="training-request-card"><div className="panel-heading"><h3>{request.people.full_name} · {request.certification_types.display_name}</h3><span className="status-badge">{request.status}</span></div>{request.people.organization&&<p>{request.people.organization}</p>}<p><a href={`mailto:${request.people.email}`}>{request.people.email}</a> · <a href={`tel:${request.contact_phone}`}>{request.contact_phone}</a></p><Appointment row={request}/>{request.student_note&&<p><strong>Client note:</strong> {request.student_note}</p>}{editable?<details><summary>{admin?'Schedule / update request':'Record session completion'}</summary><form className="portal-form" onSubmit={e=>void save(e)}>{admin&&<label className="field">Request state<select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="scheduled">Accept / schedule</option>{ended&&<option value="completed">Session completed</option>}<option value="cancelled">Cancelled</option></select></label>}{status==='scheduled'&&<><div className="form-grid"><label className="field">Session starts (Nepal)<input required type="datetime-local" name="scheduledAt" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">Session ends (Nepal)<input required type="datetime-local" name="scheduledEndAt" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label className="field">Assigned trainer<select required name="trainerId" defaultValue={request.assigned_trainer_id||''}><option value="">Choose an authorized trainer</option>{trainers.filter(t=>t.trainingTypeIds.includes(request.certification_type_id||'')).map(t=><option key={t.userId} value={t.userId}>{t.displayName}</option>)}</select></label>{changed&&<label className="check-line"><input required type="checkbox" name="contactConfirmed"/> I contacted the participant and they agreed to this changed time.</label>}</>}<label className="field">Session instructions / staff note<textarea required minLength={10} maxLength={1000} name="note" defaultValue={request.staff_note} placeholder="Meeting point, what to bring, or reason for the update"/></label>{error&&<p className="alert alert--error" role="alert">{error}</p>}<button className="button button--primary" disabled={busy}>{busy?'Saving…':'Save training request'}</button></form></details>:!admin&&request.status==='scheduled'&&<p>Record completion after the session ends. Attendance does not issue a certification.</p>}</article>;
}
export function StaffTrainingRequests({requests,onSaved,admin=false}:{requests:StaffRequest[];onSaved:()=>void;admin?:boolean}){return <section className="panel"><h2>{admin?'Training requests':'My scheduled training'}</h2><p>{admin?'Schedule requests and assign trainers in the Training requests tab.':'Accepted training assigned to you appears here with the client’s contact details and the confirmed time.'} Completing a session does not issue a certification.</p>{admin?<a className="button button--secondary" href="#/staff/training-requests">Open training requests</a>:requests.length?requests.map(request=><RequestEditor key={`${request.id}-${request.status}-${request.scheduled_at}`} request={request} onSaved={onSaved}/>):<p>No upcoming training assigned to you.</p>}</section>;}
