import { useEffect,useState } from 'react';
import { portal,message,dateTime } from './client';
import { nepalInputValue } from '../../lib/availabilityTimeline';
export interface RequestRow{id:string;status:string;contact_phone:string;availability:string;student_note:string;scheduled_at:string|null;staff_note:string;created_at:string;certification_types:{display_name:string}}
export interface StaffRequest extends RequestRow{people:{full_name:string;email:string}}
interface Data{types:Array<{id:string;display_name:string}>;requests:RequestRow[]}
export function HelpDesk(){return <p className="help-desk">Questions about training, your records or special arrangements? <a href="mailto:kec.innovation@kecktm.edu.np">Ask the Makerspace help desk</a> or <a href="https://kec-innovation.github.io/makerspace/contact.html" target="_blank" rel="noopener noreferrer">view contact details</a>.</p>;}
export function TrainingRequests({phone=''}:{phone?:string}){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;setError('');void portal<Data>('account.training').then(value=>live&&setData(value)).catch(cause=>live&&setError(message(cause)));return()=>{live=false;};},[revision]);
 async function request(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const form=e.currentTarget;try{const body=Object.fromEntries(new FormData(form));await portal('account.request-training',body);setNotice('Training requested. Staff will arrange a session using your contact number and post its time here.');form.reset();setRevision(v=>v+1);}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 async function cancel(id:string){setBusy(true);setError('');try{await portal('account.cancel-training',{requestId:id});setNotice('Training request cancelled. Your history is retained.');setRevision(v=>v+1);}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 return <section className="panel"><h2>Request equipment training</h2><p>Tell us what you want to learn and when you can attend. Staff will place you in a suitable session. Safety, waiver and equipment assessment are checked separately.</p><HelpDesk/>{error&&<p className="alert alert--error" role="alert">{error}</p>}{notice&&<p className="alert" role="status">{notice}</p>}{!data?<p role="status">{error?'Reload your account to retry.':'Loading training options…'}</p>:<><form className="portal-form" onSubmit={e=>void request(e)}><label className="field">Equipment training<select required name="certificationTypeId" defaultValue=""><option value="">Choose what you want to learn</option>{data.types.map(type=><option key={type.id} value={type.id}>{type.display_name}</option>)}</select></label><label className="field">Contact number<input required type="tel" autoComplete="tel" name="phone" minLength={7} maxLength={40} defaultValue={phone}/></label><label className="field">Preferred days and times<textarea required name="availability" minLength={10} maxLength={1000} placeholder="For example, Monday or Wednesday after 2 pm"/></label><label className="field">What do you want to make? / questions<textarea name="note" maxLength={1000}/></label><button className="button button--primary" disabled={busy}>Send training request</button></form><h3>Your training requests</h3>{!data.requests.length&&<p>No training requests yet.</p>}{data.requests.map(row=><article className="training-request-card" key={row.id}><div className="panel-heading"><strong>{row.certification_types.display_name}</strong><span className="status-badge">{row.status}</span></div><p>{row.scheduled_at?`Session: ${dateTime(row.scheduled_at)}`:`Requested ${dateTime(row.created_at)}`}</p><p>Availability: {row.availability}</p>{row.staff_note&&<p><strong>Staff instructions:</strong> {row.staff_note}</p>}{['pending','scheduled'].includes(row.status)&&<button className="button button--secondary button--small" disabled={busy} onClick={()=>void cancel(row.id)}>Cancel training request</button>}</article>)}</>}</section>;
}
function RequestEditor({request,onSaved}:{request:StaffRequest;onSaved:()=>void}){
 const [status,setStatus]=useState(request.status);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const body=Object.fromEntries(new FormData(e.currentTarget));const scheduledAt=body.scheduledAt?new Date(`${String(body.scheduledAt)}+05:45`).toISOString():null;await portal('training.request-update',{requestId:request.id,status,scheduledAt,note:body.note});onSaved();}catch(cause){setError(message(cause));}finally{setBusy(false);}}
 return <article className="training-request-card"><h3>{request.people.full_name} · {request.certification_types.display_name}</h3><p><a href={`mailto:${request.people.email}`}>{request.people.email}</a> · <a href={`tel:${request.contact_phone}`}>{request.contact_phone}</a></p><p><strong>Preferred availability:</strong> {request.availability}</p>{request.student_note&&<p>{request.student_note}</p>}<p>{request.status}{request.scheduled_at?` · ${dateTime(request.scheduled_at)}`:''}</p><details><summary>Schedule / update request</summary><form className="portal-form" onSubmit={e=>void save(e)}><label className="field">Request state<select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="scheduled">Scheduled</option><option value="completed">Session completed</option><option value="cancelled">Cancelled</option></select></label>{status==='scheduled'&&<label className="field">Session starts (Nepal)<input required type="datetime-local" name="scheduledAt" defaultValue={request.scheduled_at?nepalInputValue(request.scheduled_at):''}/></label>}<label className="field">Session instructions / staff note<textarea required minLength={10} maxLength={1000} name="note" defaultValue={request.staff_note} placeholder="Meeting point, trainer, what to bring, or reason for the update"/></label>{error&&<p className="alert alert--error" role="alert">{error}</p>}<button className="button button--primary" disabled={busy}>Save training request</button></form></details></article>;
}
export function StaffTrainingRequests({requests,onSaved}:{requests:StaffRequest[];onSaved:()=>void}){return <section className="panel"><h2>Training request queue</h2><p>Open requests for your assigned equipment training. Set the session time and instructions so the student can see the plan in My account. Completing a request does not issue a certification.</p>{requests.length?requests.map(request=><RequestEditor key={`${request.id}-${request.status}-${request.scheduled_at}`} request={request} onSaved={onSaved}/>):<p>No open requests for your training scope.</p>}</section>;}
