import { useEffect,useState } from 'react';
import { api } from '../../lib/api';
import { Modal } from '../../components/Modal';
import type { StaffSession } from '../../types/domain';
import { nepalDateTime,relation } from './adminShared';
interface Review{id:string;attempt_reference:string;status:string;score:number|null;max_score:number;pass_mark:number;passed:boolean|null;submitted_at:string|null;trainer_name_snapshot:string;legacy_source_key:string|null;people?:{full_name:string};quizzes?:{display_name:string};answers:Array<{was_correct:boolean;quiz_questions:{prompt:string};quiz_question_options:{label:string}}>}
export function TrainingReview({id,session,onClose}:{id:string|null;session:StaffSession;onClose:()=>void}){
 const [note,setNote]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [result,setResult]=useState<Review|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let live=true;setResult(null);setError('');setNotice('');setNote('');if(id)void api.admin<Review>(session,'quizzes.review',{attemptId:id}).then(data=>live&&setResult(data)).catch(cause=>live&&setError(cause instanceof Error?cause.message:'Review could not be loaded.'));return()=>{live=false;};},[id,session]);
 async function save(e:React.FormEvent){e.preventDefault();if(!id)return;setBusy(true);setError('');try{await api.admin(session,'quizzes.review-note',{attemptId:id,note});setNotice('Review note saved to audit history. Result and certifications are unchanged.');setNote('');}catch(cause){setError(cause instanceof Error?cause.message:'Review note could not be saved.');}finally{setBusy(false);}}
 return <Modal title="Training result review" open={!!id} onClose={onClose}>{error&&!result?<p className="alert alert--error" role="alert">{error}</p>:!result?<p role="status">Loading training evidence…</p>:<>{error&&<p className="alert alert--error" role="alert">{error}</p>}<h3>{relation(result.people)?.full_name||result.attempt_reference}</h3><p>{relation(result.quizzes)?.display_name} · {result.attempt_reference}</p><dl className="review-facts"><div><dt>Result</dt><dd>{result.passed===true?'Passed':result.passed===false?'Not passed':result.status} · {result.score??'—'}/{result.max_score}</dd></div><div><dt>Pass mark</dt><dd>{result.pass_mark}/{result.max_score}</dd></div><div><dt>Trainer</dt><dd>{result.trainer_name_snapshot||'Not recorded'}</dd></div><div><dt>Submitted</dt><dd>{result.submitted_at?nepalDateTime(result.submitted_at):'Not recorded'}</dd></div></dl>{result.legacy_source_key&&<p className="alert">Imported historical result. A zero score may be an import placeholder; compare the original training evidence before drawing conclusions.</p>}<h3>Recorded answers</h3>{result.answers.length?<ol className="review-answers">{result.answers.map((answer,index)=><li key={index}><strong>{relation(answer.quiz_questions)?.prompt||'Question'}</strong><p>{relation(answer.quiz_question_options)?.label||'Answer not recorded'}</p><span className={answer.was_correct?'review-correct':'review-incorrect'}>{answer.was_correct?'Correct':'Incorrect'}</span></li>)}</ol>:<p>No individual answer evidence was retained for this result. Existing certifications remain separate and unchanged.</p>}<form className="portal-form" onSubmit={e=>void save(e)}><label className="field">Review / follow-up note<textarea required minLength={10} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="button button--primary" disabled={busy}>Record review in audit history</button>{notice&&<p role="status">{notice}</p>}</form><p className="training-note"> A failed result does not authorize an equipment certificate. Arrange further training or use documented assessment evidence through the training workspace.</p><a className="button button--secondary" href="#/staff/operations" onClick={onClose}>Open training responsibilities</a></>}</Modal>;
}
