import { SortableTable } from '../../../components/SortableTable';
import { useState } from 'react';
import { AlertTriangle, Play, ShieldCheck } from 'lucide-react';
import { api } from '../../../lib/api';
import { navigate } from '../../../lib/hashRouter';
import { Modal } from '../../../components/Modal';
import { StatusBadge } from '../../../components/StatusBadge';
import type { PersonCategory } from '../../../types/domain';
import { can, CATEGORY_LABELS, LoadError, LoadingBlock, nepalDateTime, PageHeader, pretty, relation, statusTone, useAdminData, type AdminProps } from '../adminShared';

interface QuizRow { id: string; display_name: string; duration_minutes: number; question_count: number; pass_mark: number; active: boolean; version: number; notes?: string | null }
interface PersonRelation { full_name: string }
interface AttemptRow { id: string; attempt_reference: string; status: string; started_at: string; score?: number | null; max_score: number; passed?: boolean | null; trainer_name_snapshot: string; people?: PersonRelation | PersonRelation[]; quizzes?: { display_name: string } | Array<{ display_name: string }> }
interface Data { quizzes: QuizRow[]; attempts: AttemptRow[] }
interface Detail { quiz: QuizRow; questions: Array<{ prompt: string; legacy_question_id?: string | null; quiz_question_options: Array<{ label: string; is_correct: boolean }> }> }

export function TrainingPanel({ session, notify }: AdminProps) {
  const resource = useAdminData<Data>(session, 'quizzes.list');
  const [startOpen, setStartOpen] = useState(false);
  const [participant, setParticipant] = useState({ fullName: '', email: '', rollNumber: '', phone: '', organization: '', category: 'kec_student' as PersonCategory, confirmAdult: false, confirmSafetyTraining: false, confirmWaiver: false });
  const [quizId, setQuizId] = useState('');
  const [edit, setEdit] = useState<{ quiz: QuizRow; json: string; displayName: string; durationMinutes: number; passMark: number; active: boolean; notes: string } | null>(null);
  async function start(event: React.FormEvent) {
    event.preventDefault();
    try { const result = await api.startQuiz(session.accessToken, { quizId, participant }); setStartOpen(false); navigate(`/quiz/${encodeURIComponent(result.attemptToken)}`); }
    catch (cause) { notify({ type: 'error', text: cause instanceof Error ? cause.message : 'Quiz could not be started.' }); }
  }
  async function openEditor(quiz: QuizRow) {
    try {
      const detail = await api.admin<Detail>(session, 'quizzes.get', { quizId: quiz.id });
      const questions = detail.questions.map((question) => ({ prompt: question.prompt, legacyQuestionId: question.legacy_question_id || undefined, options: question.quiz_question_options.map((option) => ({ label: option.label, isCorrect: option.is_correct })) }));
      setEdit({ quiz, json: JSON.stringify(questions, null, 2), displayName: quiz.display_name, durationMinutes: quiz.duration_minutes, passMark: quiz.pass_mark, active: quiz.active, notes: quiz.notes || '' });
    } catch (cause) { notify({ type: 'error', text: cause instanceof Error ? cause.message : 'Quiz editor could not be opened.' }); }
  }
  async function saveQuiz(event: React.FormEvent) {
    event.preventDefault(); if (!edit) return;
    try {
      const questions = JSON.parse(edit.json) as unknown;
      if (!Array.isArray(questions)) throw new Error('Questions must be a JSON array.');
      const archiveReason=edit.quiz.active&&!edit.active?window.prompt('Reason for archiving this quiz (at least 10 characters)'):'';if(edit.quiz.active&&!edit.active&&!archiveReason)return;
      await api.admin(session, 'quizzes.replace', { archiveReason:archiveReason||'',quizId: edit.quiz.id, quiz: { displayName: edit.displayName, durationMinutes: edit.durationMinutes, passMark: edit.passMark, active: edit.active, notes: edit.notes, questions } });
      notify({ type: 'success', text: 'Quiz bank was replaced transactionally.' }); setEdit(null); resource.reload();
    } catch (cause) { notify({ type: 'error', text: cause instanceof Error ? cause.message : 'Quiz could not be saved.' }); }
  }
  return <>
    <PageHeader eyebrow="Supervised training" title="Training & quizzes" description="Trainer-started eight-minute assessments and immutable result history." action={can(session, 'trainer') ? <button className="button button--primary" onClick={() => setStartOpen(true)}><Play size={16} /> Start supervised quiz</button> : undefined} />
    {resource.loading && !resource.data ? <LoadingBlock label="Loading training" /> : resource.error || !resource.data ? <LoadError message={resource.error || 'Training data is unavailable.'} retry={resource.reload} /> : <><section className="quiz-admin-grid">{resource.data.quizzes.map((quiz) => <article className="panel quiz-bank-card" key={quiz.id}><div className="panel-heading"><div><h2>{quiz.display_name}</h2><p>Version {quiz.version}</p></div><StatusBadge tone={quiz.active ? 'good' : 'warn'}>{quiz.active ? 'Active' : 'Inactive'}</StatusBadge></div><dl><div><dt>Questions</dt><dd>{quiz.question_count}</dd></div><div><dt>Pass mark</dt><dd>{quiz.pass_mark}/{quiz.question_count}</dd></div><div><dt>Window</dt><dd>{quiz.duration_minutes} min</dd></div></dl>{can(session, 'admin') && <button className="button button--secondary button--wide" onClick={() => void openEditor(quiz)}>Edit quiz bank</button>}</article>)}</section><section className="panel panel--flush"><div className="panel-heading panel-heading--padded"><div><h2>Recent attempts</h2><p>Answer choices are frozen after submission</p></div></div><p className="table-sort-note">Click a heading to sort the loaded rows.</p><div className="table-scroll"><SortableTable className="data-table"><thead><tr><th>Attempt</th><th>Participant</th><th>Quiz</th><th>Trainer</th><th>Started</th><th>Result</th></tr></thead><tbody>{resource.data.attempts.map((attempt) => <tr key={attempt.id}><td><strong>{attempt.attempt_reference}</strong></td><td>{relation(attempt.people)?.full_name}</td><td>{relation(attempt.quizzes)?.display_name}</td><td>{attempt.trainer_name_snapshot}</td><td data-sort={attempt.started_at}>{nepalDateTime(attempt.started_at)}</td><td>{attempt.status === 'submitted' ? <StatusBadge tone={attempt.passed ? 'good' : 'bad'}>{attempt.score}/{attempt.max_score} · {attempt.passed ? 'Passed' : 'Failed'}</StatusBadge> : <StatusBadge tone={statusTone(attempt.status)}>{pretty(attempt.status)}</StatusBadge>}</td></tr>)}</tbody></SortableTable></div></section></>}
    <Modal title="Start supervised quiz" open={startOpen} onClose={() => setStartOpen(false)}>{resource.data && <form onSubmit={(event) => void start(event)}><div className="alert alert--warning"><ShieldCheck size={18} /> The trainer must verify the participant in person before starting.</div><div className="form-grid"><label className="field field--full"><span>Quiz</span><select required value={quizId} onChange={(event) => setQuizId(event.target.value)}><option value="">Choose an active quiz</option>{resource.data.quizzes.filter((quiz) => quiz.active).map((quiz) => <option key={quiz.id} value={quiz.id}>{quiz.display_name}</option>)}</select></label><label className="field"><span>Full name</span><input required value={participant.fullName} onChange={(event) => setParticipant({ ...participant, fullName: event.target.value })} /></label><label className="field"><span>Email</span><input required type="email" value={participant.email} onChange={(event) => setParticipant({ ...participant, email: event.target.value })} /></label><label className="field"><span>Category</span><select value={participant.category} onChange={(event) => setParticipant({ ...participant, category: event.target.value as PersonCategory })}>{Object.entries(CATEGORY_LABELS).filter(([value]) => value !== 'outreach_minor').map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field"><span>Roll number</span><input value={participant.rollNumber} onChange={(event) => setParticipant({ ...participant, rollNumber: event.target.value })} /></label><label className="field"><span>Phone</span><input required value={participant.phone} onChange={(event) => setParticipant({ ...participant, phone: event.target.value })} /></label><label className="field"><span>Organization</span><input value={participant.organization} onChange={(event) => setParticipant({ ...participant, organization: event.target.value })} /></label><label className="check-line field--full"><input required type="checkbox" checked={participant.confirmSafetyTraining} onChange={(event) => setParticipant({ ...participant, confirmSafetyTraining: event.target.checked })} /> Safety orientation completed</label><label className="check-line field--full"><input required type="checkbox" checked={participant.confirmWaiver} onChange={(event) => setParticipant({ ...participant, confirmWaiver: event.target.checked })} /> Liability waiver confirmed</label><label className="check-line field--full"><input required type="checkbox" checked={participant.confirmAdult} onChange={(event) => setParticipant({ ...participant, confirmAdult: event.target.checked })} /> Adult status verified (minors cannot receive independent access)</label></div><div className="button-row"><button type="button" className="button button--secondary" onClick={() => setStartOpen(false)}>Cancel</button><button className="button button--primary">Start 8-minute quiz</button></div></form>}</Modal>
    <Modal title={`Edit ${edit?.quiz.display_name || 'quiz'}`} open={Boolean(edit)} onClose={() => setEdit(null)}>{edit && <form onSubmit={(event) => void saveQuiz(event)}><div className="alert alert--warning"><AlertTriangle size={18} /> Saving replaces the entire bank in one transaction. Each question needs exactly one correct option.</div><div className="form-grid"><label className="field field--full"><span>Quiz name</span><input required value={edit.displayName} onChange={(event) => setEdit({ ...edit, displayName: event.target.value })} /></label><label className="field"><span>Duration minutes</span><input type="number" min="1" max="60" value={edit.durationMinutes} onChange={(event) => setEdit({ ...edit, durationMinutes: Number(event.target.value) })} /></label><label className="field"><span>Pass mark</span><input type="number" min="1" max="100" value={edit.passMark} onChange={(event) => setEdit({ ...edit, passMark: Number(event.target.value) })} /></label><label className="check-line field--full"><input type="checkbox" disabled={session.role!=='owner'&&edit.quiz.active} checked={edit.active} onChange={(event) => setEdit({ ...edit, active: event.target.checked })} /> Active for new attempts</label><label className="field field--full"><span>Questions JSON <small>private admin response; never in the public bundle</small></span><textarea className="code-editor" spellCheck="false" value={edit.json} onChange={(event) => setEdit({ ...edit, json: event.target.value })} /></label><label className="field field--full"><span>Notes</span><textarea value={edit.notes} onChange={(event) => setEdit({ ...edit, notes: event.target.value })} /></label></div><div className="button-row"><button type="button" className="button button--secondary" onClick={() => setEdit(null)}>Cancel</button><button className="button button--primary">Replace quiz bank</button></div></form>}</Modal>
  </>;
}
