import { workspaceCache } from '../../../lib/workspaceCache';
import { useEffect,useRef,useState } from 'react';
import { portal,message } from '../../portal/client';
import { RequestEditor,type StaffRequest,type TrainerOption } from '../../portal/TrainingRequests';
import { PageHeader,type AdminProps } from '../adminShared';
interface Queue{rows:StaffRequest[];total:number;pageSize:number;types:{id:string;display_name:string}[];trainers:TrainerOption[]}
export function TrainingRequestsPanel({session}:AdminProps){
 const [data,setData]=useState<Queue|null>(null);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [audience,setAudience]=useState('external');const [status,setStatus]=useState('open');const [typeId,setTypeId]=useState('');const [page,setPage]=useState(1);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const lastRevision=useRef(0);
 useEffect(()=>{const timer=window.setTimeout(()=>{setQuery(search);setPage(1);},300);return()=>window.clearTimeout(timer);},[search]);
 useEffect(()=>{let live=true;const key=`${session.userId}:${session.accessToken}:training-requests:${query}:${audience}:${status}:${typeId}:${page}`;const force=revision!==lastRevision.current;lastRevision.current=revision;const cached=force?null:workspaceCache.peek<Queue>(key);setLoading(!cached);if(cached)setData(cached);setError('');void workspaceCache.get<Queue>(key,()=>portal<Queue>('training.requests',{search:query,audience,status,typeId,page}),force).then(value=>{if(live)setData(value);}).catch(cause=>live&&setError(message(cause))).finally(()=>live&&setLoading(false));return()=>{live=false;};},[query,audience,status,typeId,page,revision,session.userId,session.accessToken]);
 return <><PageHeader eyebrow="Training appointments" title="Training requests" description="Review preferred times, contact clients when needed, then assign a trainer and accept the session. Completion and certification stay separate." action={<button className="button button--secondary" disabled={loading} onClick={()=>setRevision(v=>v+1)}>Refresh</button>}/><div className="portal-actions" role="group" aria-label="Training client group">{([['external','External clients'],['kec','KEC students & staff'],['all','All clients']] as const).map(([value,label])=><button key={value} aria-pressed={audience===value} className={`button ${audience===value?'button--primary':'button--secondary'}`} onClick={()=>{setAudience(value);setPage(1);}}>{label}</button>)}</div><section className="panel"><div className="training-filter-grid"><label className="field">Search training requests<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, email, phone or organization" maxLength={100}/></label><label className="field">Equipment training<select value={typeId} onChange={e=>{setTypeId(e.target.value);setPage(1);}}><option value="">All equipment training</option>{data?.types.map(type=><option key={type.id} value={type.id}>{type.display_name}</option>)}</select></label><label className="field">Request status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}>{[['open','Pending & scheduled'],['pending','Pending'],['scheduled','Scheduled'],['completed','Completed'],['cancelled','Cancelled'],['all','All history']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{error&&<p className="alert alert--error" role="alert">{error}<button className="text-button" onClick={()=>setRevision(v=>v+1)}>Retry</button></p>}{loading?<p role="status">Loading training requests…</p>:data&&!error&&<><p role="status">{data.total} matching request{data.total===1?'':'s'} · Page {page} of {Math.max(1,Math.ceil(data.total/data.pageSize))}</p>{data.rows.length?data.rows.map(row=><RequestEditor key={`${row.id}-${row.updated_at||''}-${row.scheduled_at}-${row.status}`} request={row} admin trainers={data.trainers} onSaved={()=>setRevision(v=>v+1)}/>):<p>No requests match these filters. Clients request training from My account after completing their profile.</p>}<div className="button-row"><button className="button button--secondary" disabled={page===1} onClick={()=>setPage(v=>v-1)}>Previous page</button><button className="button button--secondary" disabled={page*data.pageSize>=data.total} onClick={()=>setPage(v=>v+1)}>Next page</button></div></>}</section></>;
}
